require "user.impatient"
require "user.plugins"
require "user.options"
require "user.autocommands"
require "user.keymaps"
require "user.notify"
require "user.colorscheme"
require "user.lsp"
require "user.luasnip"
require "user.tabnine"
require "user.cmp"
require "user.fastaction"
require "user.treesitter"
require "user.treesitter-context"
require "user.illuminate"
-- require "user.telescope" -- init in plugins
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.lualine"
require "user.toggleterm"
require "user.indentline"
-- require "user.neotree"
-- require "user.bufferline"
-- require "user.project"
-- require "user.alpha"
-- require "user.dap"
-- require "user.neoscroll"
require "user.harpoon"
require "user.neoclip"
require "user.session"
require "user.whichkey"
-- require "user.tabout"
require "user.diffview"
require "user.surround"
require "user.git-worktree"
require "user.preview"
-- require "user.fidget"
require "user.marks"
require "user.colorizer"
require "user.buffer-close"
require "user.yabs"
-- require "user.snap"
-- require "user.winbar"
