if vim.g.vscode then
  require "user.packer_compiled"
  require "user.vscode-keymaps"
  require "user.vscode-options"
  require "user.autocommands"
  require "user.plugins"
else
--  require "user.impatient"
  require "user.packer_compiled"
  require "user.plugins"
--  require "user.lsp"
  require "user.options"
  require "user.autocommands"
  require "user.notify"
--  require "user.noice"
  require "user.keymaps"
  require "user.colorscheme"
  require "user.luasnip"
--   require "user.cmp"
--  require "user.autopairs"
--  require "user.autotag"
--  require "user.comment"
--  require "user.gitsigns"
  require "user.lualine"
--  require "user.toggleterm"
--  require "user.indentline"
--  require "user.neoscroll"
  require "user.whichkey"
--  require "user.diffview"
--  require "user.lspsaga"
--  require "user.treesitter_object"
  require "user.bufferline"
end
