require "user.impatient"
require "user.plugins"
require "user.lsp"
require "user.options"
require "user.keymaps"
require "user.autocommands"
require "user.telescope"
-- require "user.fidget"
require "user.noice"
require "user.notify"
-- require "user.prettier"
require "user.colorscheme"
require "user.luasnip"
require "user.cmp"
require "user.autopairs"
require "user.autotag"
require "user.comment"
require "user.gitsigns"
require "user.lualine"
require "user.toggleterm"
require "user.indentline"
require "user.neoscroll"
require "user.neoclip"
require "user.whichkey"
require "user.diffview"
require "user.lspsaga"
require "user.treesitter_object"
require "user.bufferline"
